{% set name = "ansitable" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansitable-{{ version }}.tar.gz
  sha256: bcc01462972e5c7d9a56f06e31fd876ada5c1ef82e2040df522e28f7fcb3abf2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - colored >=2
    - python >=3.4
    - numpy

test:
  imports:
    - ansitable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/ansitable
  summary: Quick and easy display of tabular data and matrices with optional ANSI color and borders.
  dev_url: https://github.com/petercorke/ansitable
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
