{% set name = "ansitable" %}
{% set version = "0.11.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansitable-{{ version }}.tar.gz
  sha256: 03bb1e62b3a04ef3bd9e9bc4d2f45b2a59221aa8b53fa43f98a5df58a433e1a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
  run:
    - colored >=2
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - ansitable
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/petercorke/ansitable
  summary: Quick and easy display of tabular data and matrices with optional ANSI color and borders.
  dev_url: https://github.com/petercorke/ansitable
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
