{% set name = "ansitable" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansitable-{{ version }}.tar.gz
  sha256: 9dabdac9ece44921e0c0ecac0b77db81341a851663215db8273200425f97e499

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - colored >=2
    - python >=3.7
    - numpy

test:
  imports:
    - ansitable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/ansitable
  summary: Quick and easy display of tabular data and matrices with optional ANSI color and borders.
  dev_url: https://github.com/petercorke/ansitable
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
